### ISSUE TITLE
Idea: Expo Template Support

### ISSUE THREAD

**Issue by hirbod** [victorkvarghese/react-native-zustand-boilerplate#1]
This boilerplate is send from heaven to me.
I was thinking about a good structure and if it makes sense to use react-query with zustand and you proofed that it is in fact a good idea.

I would recommend to also provide this as an expo template, since a lot of people really don't like to go vanilla rn.

I mean, it's not a big issue to copy everything to an expo structure, but would be nice to have this as a ready template.

Great work, beautiful setup, I really like it!

**Comment by victorkvarghese** [comment]
Never had a chance to use expo yet. Will try to see if i can get something ready

**Comment by hirbod** [comment]
I can just tell you: forget everything you thought you know about it. Since SDK 41 (now at 43), Expo just reached another level with EAS Build, Custom Dev Clients. I'll promise you'll love it and never look back!

P.S: you don't need to call `enableScreens()` anymore with react-navigation. 
Also would recommend you to have a look at 
`import { createNativeStackNavigator } form "@react-navigation/native-stack"`

**Comment by Dave-Wagner** [comment]
+1 for Expo support.

**Comment by consciouscoder** [comment]
+2 for Expo support 🙏

**Comment by victorkvarghese** [comment]
Hi,

I have added another branch [#expo-variant](https://github.com/victorkvarghese/react-native-query-boilerplate/tree/expo-variant)

Let me know if this helps or there is a better way to handle expo templates

CC: @hirbod  @consciouscoder @Dave-Wagner

**Comment by devh2t** [comment]
Nice work Victor, amazing work & i appreciate it.

So after running the demo ,it work fine but when i try to use the boilerplate & rename the projet using react-native-rename 
<img width="862" alt="Screenshot 2022-12-05 at 16 55 32" src="https://user-images.githubusercontent.com/118622904/205682458-e824e9b4-359e-4a21-9366-9a6b07c6e64a.png">
,i got an error :

`Invariant Violation: "RNZustandBoilerPlate" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes`



Can you check this issue plz? 

<img width="341" alt="Screenshot 2022-12-05 at 16 51 15" src="https://user-images.githubusercontent.com/118622904/205681797-a5702eaf-59a5-4093-a675-376dd98816fb.png">
<img width="662" alt="Screenshot 2022-12-05 at 16 53 56" src="https://user-images.githubusercontent.com/118622904/205681936-bb8e70fd-af0e-4168-b4be-ee5f3eae6f13.png">

**Comment by Victor-Varghese** [comment]
@devh2t it's working for me, make sure you close sever after you rename.

**Comment by victorkvarghese** [comment]
@devh2t it's working for me, make sure you close server after you rename.
